#ifndef _MULTI_DOMAIN_MODULES_BLE_NUS_SHARED_ZBUS_DEFINITION_H_
#define _MULTI_DOMAIN_MODULES_BLE_NUS_SHARED_ZBUS_DEFINITION_H_

#include "shared_zbus.h"

#if IS_ENABLED(CONFIG_ZBUS_MULTIDOMAIN)
ZBUS_MULTIDOMAIN_CHAN_DEFINE(BLE_NUS_CHAN,
			     struct ble_nus_module_message,
			     NULL,
			     NULL,
			     ZBUS_OBSERVERS_EMPTY,
			     ZBUS_MSG_INIT(0),
			     IS_ENABLED(CONFIG_MDM_BLE_NUS_RUNNER),
			     IS_ENABLED(CONFIG_MDM_BLE_NUS));
#else
ZBUS_CHAN_DEFINE(BLE_NUS_CHAN,
		 struct ble_nus_module_message,
		 NULL,
		 NULL,
		 ZBUS_OBSERVERS_EMPTY,
		 ZBUS_MSG_INIT(0));
#endif /* CONFIG_ZBUS_MULTIDOMAIN */

#endif /* _MULTI_DOMAIN_MODULES_BLE_NUS_SHARED_ZBUS_DEFINITION_H_ */
