#ifndef _MULTI_DOMAIN_MODULES_LED_SHARED_ZBUS_DEFINITION_H_
#define _MULTI_DOMAIN_MODULES_LED_SHARED_ZBUS_DEFINITION_H_

#include "shared_zbus.h"

#if IS_ENABLED(CONFIG_ZBUS_MULTIDOMAIN)
#if IS_ENABLED(CONFIG_MDM_LED_RUNNER)
#define LED_IS_SHADOW 0
#else
#define LED_IS_SHADOW 1
#endif /* CONFIG_MDM_LED_RUNNER */
ZBUS_MULTIDOMAIN_CHAN_DEFINE(LED_CHAN,
			     struct led_msg,
			     NULL,
			     NULL,
			     ZBUS_OBSERVERS_EMPTY,
			     ZBUS_MSG_INIT(0),
			     LED_IS_SHADOW,
			     IS_ENABLED(CONFIG_MDM_LED));
#else
ZBUS_CHAN_DEFINE(LED_CHAN,
		 struct led_msg,
		 NULL,
		 NULL,
		 ZBUS_OBSERVERS_EMPTY,
		 ZBUS_MSG_INIT(0));
#endif /* CONFIG_ZBUS_MULTIDOMAIN */

#endif /* _MULTI_DOMAIN_MODULES_LED_SHARED_ZBUS_DEFINITION_H_ */

